FROM centos:7

RUN yum install -y \
    autoconf \
    automake \
    doxygen \
    file \
    gcc-c++ \
    git \
    glibc-devel \
    libtool \
    make \
    maven \
    numactl-devel \
    rdma-core-devel \
    && yum clean dbcache packages

RUN mkdir -p /proj/.git
COPY .git /proj/.git
RUN cd /proj && ls -al && git reset --hard
